const {deviceWidth, isSmallDevice, deviceHeight} = require('../layout');

const FORM = {
  LOGIN: 'LOGIN',
  FORGOT_PASS_PHONE: 'FORGOT_PASS_PHONE',
  FORGOT_PASS_OTP: 'FORGOT_PASS_OTP',
  FORGOT_PASS_REENTER: 'FORGOT_PASS_REENTER',

  REGISTER_PHONE: 'REGISTER_PHONE',
  REGISTER_OTP: 'REGISTER_OTP',
  REGISTER_PASS: 'REGISTER_PASS',
  REGISTER_CHOOSE_APART: 'REGISTER_CHOOSE_APART',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
};

const WHITE_SHAPE_WIDTH = deviceWidth + 20;
const WHITE_SHAPE_HEIGHT = isSmallDevice
  ? (deviceHeight * 2.2) / 3
  : (deviceHeight * 2) / 3;

const BORDER_HEIGHT = WHITE_SHAPE_HEIGHT * 0.22;

const CIRCLE_LOGO_SIZE = deviceWidth / 3;

const STEP_BACK_MUST_CONFIRM = [
  FORM.FORGOT_PASS_OTP,
  FORM.FORGOT_PASS_REENTER,
  FORM.REGISTER_PASS,
  FORM.REGISTER_CHOOSE_APART,
];

const REGISTER_ERR_CODE = {
  SEND_OTP_FIRST: 218,
  ENTERPASS: 216,
  CHOOSE_APART: 224,
  WAIT_APPROVE: 219,
};

const LIST_REGISTER_ERR_CODE = [
  REGISTER_ERR_CODE.SEND_OTP_FIRST,
  REGISTER_ERR_CODE.ENTERPASS,
  REGISTER_ERR_CODE.CHOOSE_APART,
  REGISTER_ERR_CODE.WAIT_APPROVE,
];

const HOUSE_HOLD = 4;
const GUEST = 5;
const MEMBER = 6;

const ROLE_USER = {
  HOUSE_HOLD: HOUSE_HOLD,
  GUEST: GUEST,
  MEMBER: MEMBER,
};

const ROLE_USER_MAPPING = [
  {
    type: HOUSE_HOLD,
    title: 'houseHold',
  },
  {
    type: GUEST,
    title: 'guest',
  },
  {
    type: MEMBER,
    title: 'member',
  },
];

export {
  FORM,
  WHITE_SHAPE_HEIGHT,
  WHITE_SHAPE_WIDTH,
  BORDER_HEIGHT,
  CIRCLE_LOGO_SIZE,
  STEP_BACK_MUST_CONFIRM,
  REGISTER_ERR_CODE,
  LIST_REGISTER_ERR_CODE,
  ROLE_USER,
  ROLE_USER_MAPPING,
};
