export default {
  SPLASH: 'Splash',
  WELCOME: 'Welcome',
  LOGIN: 'Login',
  REGISTER: 'Register',
  MAIN: 'Main',
  TAB_HOME: 'Home',
  TAB_REPORT: 'Report',
  TAB_NOTI: 'Noti',
  TAB_NEWS_LETTER: 'NewsLetter',
  TAB_ACCOUNT: 'Account',
  QR_SCAN: 'QR_SCAN',
  DETAIL_NOTI: 'DetailNoti',
  MANAGER_APART: 'ManagerApart',
  APART_DETAIL: 'ApartDetail',
  QUESTION_LIST: 'QuestionList',
  QUESTION_DETAIL: 'QuestionDetail',
  CHANGE_LANG: 'ChangeLanguage',
  CHANGE_PASS: 'ChangePass',
  HAND_LIST: 'HandList',
  HAND_LIST_DETAIL: 'HandListDetail',
  NEWS_LETTER_LIST: 'NewsLetterList',
  NEWS_LETTER_DETAIL: 'NewsLetterDetail',
  NEWS_LIST: 'NewsList',
  NEWS_DETAIL: 'NewsDetail',
  UPDATE_INFO: 'UpdateInfo',
  DETAIL_BANNER: 'DetailBanner',
};
